import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
          name="description"
          content="Streamline the creation of Yup validation schemas from TypeScript interfaces and JSON objects with Interface-to-Yup. Save development time and ensure data integrity."
        />

        <meta
          name="keywords"
          content="yup to json, json to yup, interface to yup, yup converter, yup schema creation, yup schema maker online"
        />

        <meta
          property="og:title"
          content="Interface-to-Yup - Streamlining Yup Validation Schema Generation"
        />
        <meta
          property="og:description"
          content="Streamline the creation of Yup validation schemas from TypeScript interfaces and JSON objects with Interface-to-Yup. Save development time and ensure data integrity."
        />
        <meta
          property="og:url"
          content="https://interface-to-yup.harshgoel.me/"
        />

        <meta name="twitter:card" content="summary" />
        <meta
          name="twitter:title"
          content="Interface-to-Yup - Streamlining Yup Validation Schema Generation"
        />
        <meta
          name="twitter:description"
          content="Streamline the creation of Yup validation schemas from TypeScript interfaces and JSON objects with Interface-to-Yup. Save development time and ensure data integrity."
        />

        <meta name="robots" content="index, follow" />
        <meta httpEquiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="language" content="English" />
        <meta name="revisit-after" content="10 days" />
        <meta name="author" content="Harsh Goel" />
        <meta name="copyright" content="All rights reserved,2021. Harsh Goel" />
        <meta httpEquiv="content-language" content="en" />
        <title>Interface-to-Yup</title>
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
